# Generated by Django 3.1.1 on 2020-11-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='major_category',
            field=models.CharField(default=(), max_length=40),
        ),
    ]
