# Generated by Django 3.1.1 on 2020-11-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20201124_0219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='major_category',
            field=models.CharField(default=({'first_major': '스마트ICT융합공학과'},), max_length=40),
        ),
    ]
