# Generated by Django 3.1.1 on 2020-11-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20201124_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='major_category',
            field=models.CharField(max_length=40),
        ),
    ]
