# Generated by Django 3.1.1 on 2020-11-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20201124_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kakaoUrl',
            field=models.URLField(default='', help_text='생성한 오픈 카카오톡 링크를 작성해 주세요'),
        ),
    ]
