# Generated by Django 3.1.1 on 2020-12-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_book_kakaourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='deal',
            field=models.IntegerField(default=1),
        ),
    ]
