# Generated by Django 3.1.1 on 2020-12-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20201228_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='deal',
        ),
        migrations.AddField(
            model_name='book',
            name='deal_flag',
            field=models.CharField(default='거래중', max_length=10),
        ),
    ]
