# Generated by Django 3.1.1 on 2020-12-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20201228_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='deal_flag',
            field=models.BooleanField(default=1),
        ),
    ]
