# Generated by Django 3.1.1 on 2021-01-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_auto_20210103_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='state',
            field=models.CharField(choices=[('A', '최상'), ('B', '상'), ('C', '보통'), ('D', '하')], max_length=10),
        ),
    ]
