# Generated by Django 3.1.1 on 2021-01-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20210105_1245'),
        ('book', '0017_auto_20210104_1609'),
    ]

    operations = [
    ]
