# Generated by Django 3.1.1 on 2021-01-11 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0018_merge_20210108_2112'),
        ('book', '0018_merge_20210106_1841'),
    ]

    operations = [
    ]
