# Generated by Django 3.1.1 on 2021-01-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201124_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('female', '여'), ('male', '남')], default='', max_length=6),
        ),
    ]
