# Generated by Django 3.1.1 on 2020-11-24 18:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AllBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='제목')),
                ('lecture', models.CharField(max_length=50, null=True, verbose_name='수업')),
                ('text', models.TextField(verbose_name='게시글')),
                ('state', models.CharField(choices=[('A', '아주좋음'), ('B', '좋음'), ('C', '보통'), ('D', '나쁨')], max_length=10)),
                ('price', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, upload_to='timeline_all_post/%Y/%m/%d')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('kakaoUrl', models.URLField(default='', help_text='생성한 오픈 카카오톡 링크를 작성해 주세요')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
